var chordNotes = [
{"chorld":"C","level":"Major","chord":"C,E,G","note1":"C","note2":"E","note3":"G"},
{"chorld":"Cm","level":"Minor","chord":"C,Eb,G","note1":"C","note2":"Eb","note3":"G"},
{"chorld":"C7","level":"Aug","chord":"C,E,G#","note1":"C","note2":"E","note3":"G#"},
{"chorld":"C#","level":"Major","chord":"C#,F,Ab","note1":"C#","note2":"F","note3":"Ab"},
{"chorld":"C#m","level":"Minor","chord":"C#,E,Ab","note1":"C#","note2":"E","note3":"Ab"},
{"chorld":"C#7","level":"Aug","chord":"C#,F,A","note1":"C#","note2":"F","note3":"A"},
{"chorld":"Db","level":"Major","chord":"Db,F,Ab","note1":"Db","note2":"F","note3":"Ab"},
{"chorld":"Dbm","level":"Minor","chord":"Db,E,Ab","note1":"Db","note2":"E","note3":"Ab"},
{"chorld":"Db7","level":"Aug","chord":"Db,F,A","note1":"Db","note2":"F","note3":"A"},
{"chorld":"D","level":"Major","chord":"D,F#,A","note1":"D","note2":"F#","note3":"A"},
{"chorld":"Dm","level":"Minor","chord":"D,F,A","note1":"D","note2":"F","note3":"A"},
{"chorld":"D7","level":"Aug","chord":"D,F#,Bb","note1":"D","note2":"F#","note3":"Bb"},
{"chorld":"D#","level":"Major","chord":"D#,G,Bb","note1":"D#","note2":"G","note3":"Bb"},
{"chorld":"D#m","level":"Minor","chord":"D#,Gb,Bb","note1":"D#","note2":"Gb","note3":"Bb"},
{"chorld":"D#7","level":"Aug","chord":"D#,G,B","note1":"D#","note2":"G","note3":"B"},
{"chorld":"Eb","level":"Major","chord":"Eb,G,Bb","note1":"Eb","note2":"G","note3":"Bb"},
{"chorld":"Ebm","level":"Minor","chord":"Eb,Gb,Bb","note1":"Eb","note2":"Gb","note3":"Bb"},
{"chorld":"Eb7","level":"Aug","chord":"Eb,G,B","note1":"Eb","note2":"G","note3":"B"},
{"chorld":"E","level":"Major","chord":"E,G#,B","note1":"E","note2":"G#","note3":"B"},
{"chorld":"Em","level":"Minor","chord":"E,G,B","note1":"E","note2":"G","note3":"B"},
{"chorld":"E7","level":"Aug","chord":"E,G#,C","note1":"E","note2":"G#","note3":"C"},
{"chorld":"F","level":"Major","chord":"F,A,C","note1":"F","note2":"A","note3":"C"},
{"chorld":"Fm","level":"Minor","chord":"F,Ab,C","note1":"F","note2":"Ab","note3":"C"},
{"chorld":"F7","level":"Aug","chord":"F,A,C#","note1":"F","note2":"A","note3":"C#"},
{"chorld":"F#","level":"Major","chord":"F#,Bb,Db","note1":"F#","note2":"Bb","note3":"Db"},
{"chorld":"F#m","level":"Minor","chord":"F#,A,Db","note1":"F#","note2":"A","note3":"Db"},
{"chorld":"F#7","level":"Aug","chord":"F#,Bb,D","note1":"F#","note2":"Bb","note3":"D"},
{"chorld":"Gb","level":"Major","chord":"Gb,Bb,Db","note1":"Gb","note2":"Bb","note3":"Db"},
{"chorld":"Gbm","level":"Minor","chord":"Gb,A,Db","note1":"Gb","note2":"A","note3":"Db"},
{"chorld":"Gb7","level":"Aug","chord":"Gb,Bb,D","note1":"Gb","note2":"Bb","note3":"D"},
{"chorld":"G","level":"Major","chord":"G,B,D","note1":"G","note2":"B","note3":"D"},
{"chorld":"Gm","level":"Minor","chord":"G,Bb,D","note1":"G","note2":"Bb","note3":"D"},
{"chorld":"G7","level":"Aug","chord":"G,B,D#","note1":"G","note2":"B","note3":"D#"},
{"chorld":"Ab","level":"Major","chord":"Ab,C,Eb","note1":"Ab","note2":"C","note3":"Eb"},
{"chorld":"Abm","level":"Minor","chord":"Ab,B,Eb","note1":"Ab","note2":"B","note3":"Eb"},
{"chorld":"Ab7","level":"Aug","chord":"Ab,C,E","note1":"Ab","note2":"C","note3":"E"},
{"chorld":"G#","level":"Major","chord":"G#,C,Eb","note1":"G#","note2":"C","note3":"Eb"},
{"chorld":"G#m","level":"Minor","chord":"G#,B,Eb","note1":"G#","note2":"B","note3":"Eb"},
{"chorld":"G#7","level":"Aug","chord":"G#,C,E","note1":"G#","note2":"C","note3":"E"},
{"chorld":"A","level":"Major","chord":"A,C#,E","note1":"A","note2":"C#","note3":"E"},
{"chorld":"Am","level":"Minor","chord":"A,C,E","note1":"A","note2":"C","note3":"E"},
{"chorld":"A7","level":"Aug","chord":"A,C#,F","note1":"A","note2":"C#","note3":"F"},
{"chorld":"A#","level":"Major","chord":"A#,D,F","note1":"A#","note2":"D","note3":"F"},
{"chorld":"A#m","level":"Minor","chord":"A#, Db,F","note1":"A#","note2":"Db","note3":"F"},
{"chorld":"A#7","level":"Aug","chord":"A#,D,Gb","note1":"A#","note2":"D","note3":"Gb"},
{"chorld":"Bb","level":"Major","chord":"Bb,D,F","note1":"Bb","note2":"D","note3":"F"},
{"chorld":"Bbm","level":"Minor","chord":"Bb, Db,F","note1":"Bb","note2":"Db","note3":"F"},
{"chorld":"Bb7","level":"Aug","chord":"Bb,D,Gb","note1":"Bb","note2":"D","note3":"Gb"},
{"chorld":"B","level":"Major","chord":"B,D#,F#","note1":"B","note2":"D#","note3":"F#"},
{"chorld":"Bm","level":"Minor","chord":"B,D,F#","note1":"B","note2":"D","note3":"F#"},
{"chorld":"B7","level":"Aug","chord":"B,D#,G","note1":"B","note2":"D#","note3":"G"}
];
var chordNotesDb = TAFFY(chordNotes);
var chordList = [
{"genere":"rock","number":"8","chord":"A;A#;Am;Bm;C;F;Fm;G","note1":"A","note2":"A#","note3":"Am","note4":"Bm","note5":"C","note6":"F","note7":"Fm","note8":"G"},
{"genere":"rock","number":"8","chord":"A;A#;Am;C;Dm;F;G;Gm","note1":"A","note2":"A#","note3":"Am","note4":"C","note5":"Dm","note6":"F","note7":"G","note8":"Gm"},
{"genere":"soul","number":"8","chord":"A;A#;Am;C;Dm;F;G;Gm","note1":"A","note2":"A#","note3":"Am","note4":"C","note5":"Dm","note6":"F","note7":"G","note8":"Gm"},
{"genere":"pop","number":"8","chord":"A;A#;Bm;D;Em;F;F#;G","note1":"A","note2":"A#","note3":"Bm","note4":"D","note5":"Em","note6":"F","note7":"F#","note8":"G"},
{"genere":"rock","number":"8","chord":"A;Am;B;Bm;C#m;D;E;G","note1":"A","note2":"Am","note3":"B","note4":"Bm","note5":"C#m","note6":"D","note7":"E","note8":"G"},
{"genere":"rock","number":"8","chord":"A;Am;B;C;D;E;F#;G","note1":"A","note2":"Am","note3":"B","note4":"C","note5":"D","note6":"E","note7":"F#","note8":"G"},
{"genere":"rock","number":"8","chord":"A;Am;B;C;Dm;Em;F;G","note1":"A","note2":"Am","note3":"B","note4":"C","note5":"Dm","note6":"Em","note7":"F","note8":"G"},
{"genere":"rock","number":"8","chord":"A;Am;Bm;C;D;Em;F;G","note1":"A","note2":"Am","note3":"Bm","note4":"C","note5":"D","note6":"Em","note7":"F","note8":"G"},
{"genere":"pop","number":"8","chord":"A;Am;Bm;C;D;Em;F;G","note1":"A","note2":"Am","note3":"Bm","note4":"C","note5":"D","note6":"Em","note7":"F","note8":"G"},
{"genere":"rock","number":"8","chord":"A;Am;C;D;Dm;E;F;G","note1":"A","note2":"Am","note3":"C","note4":"D","note5":"Dm","note6":"E","note7":"F","note8":"G"},
{"genere":"pop","number":"8","chord":"A;Am;C;D;Dm;E;F;G","note1":"A","note2":"Am","note3":"C","note4":"D","note5":"Dm","note6":"E","note7":"F","note8":"G"},
{"genere":"pop","number":"8","chord":"A;Am;C;Dm;Em;F;G;Gm","note1":"A","note2":"Am","note3":"C","note4":"Dm","note5":"Em","note6":"F","note7":"G","note8":"Gm"},
{"genere":"pop","number":"8","chord":"A;B;C#;C#m;D#;E;F#m;Fm","note1":"A","note2":"B","note3":"C#","note4":"C#m","note5":"D#","note6":"E","note7":"F#m","note8":"Fm"},
{"genere":"rock","number":"8","chord":"A;Bm;C#m;D;Dm;E;F#m;G","note1":"A","note2":"Bm","note3":"C#m","note4":"D","note5":"Dm","note6":"E","note7":"F#m","note8":"G"},
{"genere":"soul","number":"8","chord":"A;C;D;E;Em;F;Fm;G","note1":"A","note2":"C","note3":"D","note4":"E","note5":"Em","note6":"F","note7":"Fm","note8":"G"},
{"genere":"rock","number":"8","chord":"A#;Am;C;C#;F;F#;G;G#","note1":"A#","note2":"Am","note3":"C","note4":"C#","note5":"F","note6":"F#","note7":"G","note8":"G#"},
{"genere":"soul","number":"8","chord":"A#;Am;C;D;Dm;Em;F;G","note1":"A#","note2":"Am","note3":"C","note4":"D","note5":"Dm","note6":"Em","note7":"F","note8":"G"},
{"genere":"soul","number":"8","chord":"A#;Am;C;Dm;Em;F;G;Gm","note1":"A#","note2":"Am","note3":"C","note4":"Dm","note5":"Em","note6":"F","note7":"G","note8":"Gm"},
{"genere":"rock","number":"8","chord":"A#;C;D;D#;Em;F;G;Gm","note1":"A#","note2":"C","note3":"D","note4":"D#","note5":"Em","note6":"F","note7":"G","note8":"Gm"},
{"genere":"rock","number":"8","chord":"Am;C;D;Dm;E;F;Fm;G","note1":"Am","note2":"C","note3":"D","note4":"Dm","note5":"E","note6":"F","note7":"Fm","note8":"G"},
{"genere":"rock","number":"4","chord":"A;B;C#m;E","note1":"A","note2":"B","note3":"C#m","note4":"E","note5":"A","note6":"B","note7":"C#m","note8":"E"},
{"genere":"pop","number":"4","chord":"A;B;C#m;E","note1":"A","note2":"B","note3":"C#m","note4":"E","note5":"A","note6":"B","note7":"C#m","note8":"E"},
{"genere":"soul","number":"4","chord":"A;B;C#m;E","note1":"A","note2":"B","note3":"C#m","note4":"E","note5":"A","note6":"B","note7":"C#m","note8":"E"},
{"genere":"rock","number":"4","chord":"A;B;D;E","note1":"A","note2":"B","note3":"D","note4":"E","note5":"A","note6":"B","note7":"D","note8":"E"},
{"genere":"country","number":"4","chord":"A;B;E;F#","note1":"A","note2":"B","note3":"E","note4":"F#","note5":"A","note6":"B","note7":"E","note8":"F#"},
{"genere":"rock","number":"4","chord":"A;Bm;D;E","note1":"A","note2":"Bm","note3":"D","note4":"E","note5":"A","note6":"Bm","note7":"D","note8":"E"},
{"genere":"pop","number":"4","chord":"A;Bm;D;Em","note1":"A","note2":"Bm","note3":"D","note4":"Em","note5":"A","note6":"Bm","note7":"D","note8":"Em"},
{"genere":"rock","number":"4","chord":"A;Bm;D;G","note1":"A","note2":"Bm","note3":"D","note4":"G","note5":"A","note6":"Bm","note7":"D","note8":"G"},
{"genere":"pop","number":"4","chord":"A;Bm;D;G","note1":"A","note2":"Bm","note3":"D","note4":"G","note5":"A","note6":"Bm","note7":"D","note8":"G"},
{"genere":"soul","number":"4","chord":"A;Bm;D;G","note1":"A","note2":"Bm","note3":"D","note4":"G","note5":"A","note6":"Bm","note7":"D","note8":"G"},
{"genere":"rock","number":"4","chord":"A;C;D;E","note1":"A","note2":"C","note3":"D","note4":"E","note5":"A","note6":"C","note7":"D","note8":"E"},
{"genere":"rock","number":"4","chord":"A;C;D;Em","note1":"A","note2":"C","note3":"D","note4":"Em","note5":"A","note6":"C","note7":"D","note8":"Em"},
{"genere":"rock","number":"4","chord":"A;C;D;G","note1":"A","note2":"C","note3":"D","note4":"G","note5":"A","note6":"C","note7":"D","note8":"G"},
{"genere":"rock","number":"4","chord":"A;C;E;G","note1":"A","note2":"C","note3":"E","note4":"G","note5":"A","note6":"C","note7":"E","note8":"G"},
{"genere":"country","number":"4","chord":"A;C#m;D;E","note1":"A","note2":"C#m","note3":"D","note4":"E","note5":"A","note6":"C#m","note7":"D","note8":"E"},
{"genere":"pop","number":"4","chord":"A;D;E;F#m","note1":"A","note2":"D","note3":"E","note4":"F#m","note5":"A","note6":"D","note7":"E","note8":"F#m"},
{"genere":"rock","number":"4","chord":"A;D;E;G","note1":"A","note2":"D","note3":"E","note4":"G","note5":"A","note6":"D","note7":"E","note8":"G"},
{"genere":"country","number":"4","chord":"A;D;E;G","note1":"A","note2":"D","note3":"E","note4":"G","note5":"A","note6":"D","note7":"E","note8":"G"},
{"genere":"soul","number":"4","chord":"A;D;E;G","note1":"A","note2":"D","note3":"E","note4":"G","note5":"A","note6":"D","note7":"E","note8":"G"},
{"genere":"rock","number":"4","chord":"A;D;Em;G","note1":"A","note2":"D","note3":"Em","note4":"G","note5":"A","note6":"D","note7":"Em","note8":"G"},
{"genere":"pop","number":"4","chord":"A;D;Em;G","note1":"A","note2":"D","note3":"Em","note4":"G","note5":"A","note6":"D","note7":"Em","note8":"G"},
{"genere":"country","number":"4","chord":"A;D;Em;G","note1":"A","note2":"D","note3":"Em","note4":"G","note5":"A","note6":"D","note7":"Em","note8":"G"},
{"genere":"soul","number":"4","chord":"A;D;Em;G","note1":"A","note2":"D","note3":"Em","note4":"G","note5":"A","note6":"D","note7":"Em","note8":"G"},
{"genere":"rock","number":"4","chord":"A;D;F;G","note1":"A","note2":"D","note3":"F","note4":"G","note5":"A","note6":"D","note7":"F","note8":"G"},
{"genere":"pop","number":"4","chord":"A#;Am;C;Dm","note1":"A#","note2":"Am","note3":"C","note4":"Dm","note5":"A#","note6":"Am","note7":"C","note8":"Dm"},
{"genere":"soul","number":"4","chord":"A#;Am;C;Dm","note1":"A#","note2":"Am","note3":"C","note4":"Dm","note5":"A#","note6":"Am","note7":"C","note8":"Dm"},
{"genere":"soul","number":"4","chord":"A#;Am;Dm;F","note1":"A#","note2":"Am","note3":"Dm","note4":"F","note5":"A#","note6":"Am","note7":"Dm","note8":"F"},
{"genere":"rock","number":"4","chord":"A#;C;D;G","note1":"A#","note2":"C","note3":"D","note4":"G","note5":"A#","note6":"C","note7":"D","note8":"G"},
{"genere":"rock","number":"4","chord":"A#;C;Dm;F","note1":"A#","note2":"C","note3":"Dm","note4":"F","note5":"A#","note6":"C","note7":"Dm","note8":"F"},
{"genere":"pop","number":"4","chord":"A#;C;Dm;F","note1":"A#","note2":"C","note3":"Dm","note4":"F","note5":"A#","note6":"C","note7":"Dm","note8":"F"},
{"genere":"country","number":"4","chord":"A#;C;Dm;F","note1":"A#","note2":"C","note3":"Dm","note4":"F","note5":"A#","note6":"C","note7":"Dm","note8":"F"},
{"genere":"soul","number":"4","chord":"A#;C;Dm;F","note1":"A#","note2":"C","note3":"Dm","note4":"F","note5":"A#","note6":"C","note7":"Dm","note8":"F"},
{"genere":"rock","number":"4","chord":"A#;C;Dm;G","note1":"A#","note2":"C","note3":"Dm","note4":"G","note5":"A#","note6":"C","note7":"Dm","note8":"G"},
{"genere":"pop","number":"4","chord":"A#;C;Dm;Gm","note1":"A#","note2":"C","note3":"Dm","note4":"Gm","note5":"A#","note6":"C","note7":"Dm","note8":"Gm"},
{"genere":"soul","number":"4","chord":"A#;C;F;G","note1":"A#","note2":"C","note3":"F","note4":"G","note5":"A#","note6":"C","note7":"F","note8":"G"},
{"genere":"soul","number":"4","chord":"A#;Dm;F;G","note1":"A#","note2":"Dm","note3":"F","note4":"G","note5":"A#","note6":"Dm","note7":"F","note8":"G"},
{"genere":"rock","number":"4","chord":"Am;B;C;Em","note1":"Am","note2":"B","note3":"C","note4":"Em","note5":"Am","note6":"B","note7":"C","note8":"Em"},
{"genere":"pop","number":"4","chord":"Am;Bm;C;D","note1":"Am","note2":"Bm","note3":"C","note4":"D","note5":"Am","note6":"Bm","note7":"C","note8":"D"},
{"genere":"pop","number":"4","chord":"Am;Bm;C;Em","note1":"Am","note2":"Bm","note3":"C","note4":"Em","note5":"Am","note6":"Bm","note7":"C","note8":"Em"},
{"genere":"soul","number":"4","chord":"Am;Bm;C;G","note1":"Am","note2":"Bm","note3":"C","note4":"G","note5":"Am","note6":"Bm","note7":"C","note8":"G"},
{"genere":"soul","number":"4","chord":"Am;Bm;Em;G","note1":"Am","note2":"Bm","note3":"Em","note4":"G","note5":"Am","note6":"Bm","note7":"Em","note8":"G"},
{"genere":"soul","number":"4","chord":"Am;C;D;E","note1":"Am","note2":"C","note3":"D","note4":"E","note5":"Am","note6":"C","note7":"D","note8":"E"},
{"genere":"pop","number":"4","chord":"Am;C;D;Em","note1":"Am","note2":"C","note3":"D","note4":"Em","note5":"Am","note6":"C","note7":"D","note8":"Em"},
{"genere":"rock","number":"4","chord":"Am;C;D;G","note1":"Am","note2":"C","note3":"D","note4":"G","note5":"Am","note6":"C","note7":"D","note8":"G"},
{"genere":"pop","number":"4","chord":"Am;C;D;G","note1":"Am","note2":"C","note3":"D","note4":"G","note5":"Am","note6":"C","note7":"D","note8":"G"},
{"genere":"country","number":"4","chord":"Am;C;D;G","note1":"Am","note2":"C","note3":"D","note4":"G","note5":"Am","note6":"C","note7":"D","note8":"G"},
{"genere":"soul","number":"4","chord":"Am;C;D;G","note1":"Am","note2":"C","note3":"D","note4":"G","note5":"Am","note6":"C","note7":"D","note8":"G"},
{"genere":"rock","number":"4","chord":"Am;C;Dm;F","note1":"Am","note2":"C","note3":"Dm","note4":"F","note5":"Am","note6":"C","note7":"Dm","note8":"F"},
{"genere":"pop","number":"4","chord":"Am;C;Dm;F","note1":"Am","note2":"C","note3":"Dm","note4":"F","note5":"Am","note6":"C","note7":"Dm","note8":"F"},
{"genere":"rock","number":"4","chord":"Am;C;Em;F","note1":"Am","note2":"C","note3":"Em","note4":"F","note5":"Am","note6":"C","note7":"Em","note8":"F"},
{"genere":"pop","number":"4","chord":"Am;C;Em;F","note1":"Am","note2":"C","note3":"Em","note4":"F","note5":"Am","note6":"C","note7":"Em","note8":"F"},
{"genere":"soul","number":"4","chord":"Am;C;Em;F","note1":"Am","note2":"C","note3":"Em","note4":"F","note5":"Am","note6":"C","note7":"Em","note8":"F"},
{"genere":"pop","number":"4","chord":"Am;C;Em;Fm","note1":"Am","note2":"C","note3":"Em","note4":"Fm","note5":"Am","note6":"C","note7":"Em","note8":"Fm"},
{"genere":"rock","number":"4","chord":"Am;C;Em;G","note1":"Am","note2":"C","note3":"Em","note4":"G","note5":"Am","note6":"C","note7":"Em","note8":"G"},
{"genere":"pop","number":"4","chord":"Am;C;Em;G","note1":"Am","note2":"C","note3":"Em","note4":"G","note5":"Am","note6":"C","note7":"Em","note8":"G"},
{"genere":"country","number":"4","chord":"Am;C;Em;G","note1":"Am","note2":"C","note3":"Em","note4":"G","note5":"Am","note6":"C","note7":"Em","note8":"G"},
{"genere":"rock","number":"4","chord":"Am;C;F;G","note1":"Am","note2":"C","note3":"F","note4":"G","note5":"Am","note6":"C","note7":"F","note8":"G"},
{"genere":"pop","number":"4","chord":"Am;C;F;G","note1":"Am","note2":"C","note3":"F","note4":"G","note5":"Am","note6":"C","note7":"F","note8":"G"},
{"genere":"country","number":"4","chord":"Am;C;F;G","note1":"Am","note2":"C","note3":"F","note4":"G","note5":"Am","note6":"C","note7":"F","note8":"G"},
{"genere":"soul","number":"4","chord":"Am;C;F;G","note1":"Am","note2":"C","note3":"F","note4":"G","note5":"Am","note6":"C","note7":"F","note8":"G"},
{"genere":"rock","number":"4","chord":"Am;D;Em;G","note1":"Am","note2":"D","note3":"Em","note4":"G","note5":"Am","note6":"D","note7":"Em","note8":"G"},
{"genere":"pop","number":"4","chord":"Am;D;Em;G","note1":"Am","note2":"D","note3":"Em","note4":"G","note5":"Am","note6":"D","note7":"Em","note8":"G"},
{"genere":"pop","number":"4","chord":"Am;D;F;G","note1":"Am","note2":"D","note3":"F","note4":"G","note5":"Am","note6":"D","note7":"F","note8":"G"},
{"genere":"pop","number":"4","chord":"Am;Dm;Em;F","note1":"Am","note2":"Dm","note3":"Em","note4":"F","note5":"Am","note6":"Dm","note7":"Em","note8":"F"},
{"genere":"soul","number":"4","chord":"Am;Dm;Em;G","note1":"Am","note2":"Dm","note3":"Em","note4":"G","note5":"Am","note6":"Dm","note7":"Em","note8":"G"},
{"genere":"rock","number":"4","chord":"Am;Dm;F;G","note1":"Am","note2":"Dm","note3":"F","note4":"G","note5":"Am","note6":"Dm","note7":"F","note8":"G"},
{"genere":"pop","number":"4","chord":"Am;Dm;F;G","note1":"Am","note2":"Dm","note3":"F","note4":"G","note5":"Am","note6":"Dm","note7":"F","note8":"G"},
{"genere":"rock","number":"4","chord":"Am;E;F;G","note1":"Am","note2":"E","note3":"F","note4":"G","note5":"Am","note6":"E","note7":"F","note8":"G"},
{"genere":"rock","number":"4","chord":"Am;Em;F;G","note1":"Am","note2":"Em","note3":"F","note4":"G","note5":"Am","note6":"Em","note7":"F","note8":"G"},
{"genere":"pop","number":"4","chord":"Am;Em;F;G","note1":"Am","note2":"Em","note3":"F","note4":"G","note5":"Am","note6":"Em","note7":"F","note8":"G"},
{"genere":"soul","number":"4","chord":"Am;Em;F;G","note1":"Am","note2":"Em","note3":"F","note4":"G","note5":"Am","note6":"Em","note7":"F","note8":"G"},
{"genere":"rock","number":"4","chord":"B;C;Cm;G","note1":"B","note2":"C","note3":"Cm","note4":"G","note5":"B","note6":"C","note7":"Cm","note8":"G"},
{"genere":"pop","number":"4","chord":"B;E;F#;F#m","note1":"B","note2":"E","note3":"F#","note4":"F#m","note5":"B","note6":"E","note7":"F#","note8":"F#m"},
{"genere":"pop","number":"4","chord":"Bm;C;Em;G","note1":"Bm","note2":"C","note3":"Em","note4":"G","note5":"Bm","note6":"C","note7":"Em","note8":"G"},
{"genere":"rock","number":"4","chord":"Bm;D;E;G","note1":"Bm","note2":"D","note3":"E","note4":"G","note5":"Bm","note6":"D","note7":"E","note8":"G"},
{"genere":"rock","number":"4","chord":"C;D;E;G","note1":"C","note2":"D","note3":"E","note4":"G","note5":"C","note6":"D","note7":"E","note8":"G"},
{"genere":"country","number":"4","chord":"C;D;E;G","note1":"C","note2":"D","note3":"E","note4":"G","note5":"C","note6":"D","note7":"E","note8":"G"},
{"genere":"rock","number":"4","chord":"C;D;Em;G","note1":"C","note2":"D","note3":"Em","note4":"G","note5":"C","note6":"D","note7":"Em","note8":"G"},
{"genere":"pop","number":"4","chord":"C;D;Em;G","note1":"C","note2":"D","note3":"Em","note4":"G","note5":"C","note6":"D","note7":"Em","note8":"G"},
{"genere":"country","number":"4","chord":"C;D;Em;G","note1":"C","note2":"D","note3":"Em","note4":"G","note5":"C","note6":"D","note7":"Em","note8":"G"},
{"genere":"soul","number":"4","chord":"C;D;Em;G","note1":"C","note2":"D","note3":"Em","note4":"G","note5":"C","note6":"D","note7":"Em","note8":"G"},
{"genere":"rock","number":"4","chord":"C;D;F;G","note1":"C","note2":"D","note3":"F","note4":"G","note5":"C","note6":"D","note7":"F","note8":"G"},
{"genere":"pop","number":"4","chord":"C;D;F;G","note1":"C","note2":"D","note3":"F","note4":"G","note5":"C","note6":"D","note7":"F","note8":"G"},
{"genere":"soul","number":"4","chord":"C;D;F;G","note1":"C","note2":"D","note3":"F","note4":"G","note5":"C","note6":"D","note7":"F","note8":"G"},
{"genere":"soul","number":"4","chord":"C;Dm;Em;F","note1":"C","note2":"Dm","note3":"Em","note4":"F","note5":"C","note6":"Dm","note7":"Em","note8":"F"},
{"genere":"pop","number":"4","chord":"C;Dm;F;G","note1":"C","note2":"Dm","note3":"F","note4":"G","note5":"C","note6":"Dm","note7":"F","note8":"G"}
];
let chordListDb = TAFFY(chordList);
let chordTrie = {"A":{"A#":{"Am":{"Bm":[{"genere":"rock"}],"C":[{"genere":"rock"},{"genere":"soul"}]},"Bm":{"D":[{"genere":"pop"}]}},"Am":{"B":{"Bm":[{"genere":"rock"}],"C":[{"genere":"rock"},{"genere":"rock"}]},"Bm":{"C":[{"genere":"rock"},{"genere":"pop"}]},"C":{"D":[{"genere":"rock"},{"genere":"pop"}],"Dm":[{"genere":"pop"}]}},"B":{"C#":{"C#m":[{"genere":"pop"}]},"C#m":{"E":[{"genere":"rock"},{"genere":"pop"},{"genere":"soul"}]},"D":{"E":[{"genere":"rock"}]},"E":{"F#":[{"genere":"country"}]}},"Bm":{"C#m":{"D":[{"genere":"rock"}]},"D":{"E":[{"genere":"rock"}],"Em":[{"genere":"pop"}],"G":[{"genere":"rock"},{"genere":"pop"},{"genere":"soul"}]}},"C":{"D":{"E":[{"genere":"soul"},{"genere":"rock"}],"Em":[{"genere":"rock"}],"G":[{"genere":"rock"}]},"E":{"G":[{"genere":"rock"}]}},"C#m":{"D":{"E":[{"genere":"country"}]}},"D":{"E":{"F#m":[{"genere":"pop"}],"G":[{"genere":"rock"},{"genere":"country"},{"genere":"soul"}]},"Em":{"G":[{"genere":"rock"},{"genere":"pop"},{"genere":"country"},{"genere":"soul"}]},"F":{"G":[{"genere":"rock"}]}}},"A#":{"Am":{"C":{"C#":[{"genere":"rock"}],"D":[{"genere":"soul"}],"Dm":[{"genere":"soul"},{"genere":"pop"},{"genere":"soul"}]},"Dm":{"F":[{"genere":"soul"}]}},"C":{"D":{"D#":[{"genere":"rock"}],"G":[{"genere":"rock"}]},"Dm":{"F":[{"genere":"rock"},{"genere":"pop"},{"genere":"country"},{"genere":"soul"}],"G":[{"genere":"rock"}],"Gm":[{"genere":"pop"}]},"F":{"G":[{"genere":"soul"}]}},"Dm":{"F":{"G":[{"genere":"soul"}]}}},"Am":{"C":{"D":{"Dm":[{"genere":"rock"}],"E":[{"genere":"soul"}],"Em":[{"genere":"pop"}],"G":[{"genere":"rock"},{"genere":"pop"},{"genere":"country"},{"genere":"soul"}]},"Dm":{"F":[{"genere":"rock"},{"genere":"pop"}]},"Em":{"F":[{"genere":"rock"},{"genere":"pop"},{"genere":"soul"}],"Fm":[{"genere":"pop"}],"G":[{"genere":"rock"},{"genere":"pop"},{"genere":"country"}]},"F":{"G":[{"genere":"rock"},{"genere":"pop"},{"genere":"country"},{"genere":"soul"}]}},"B":{"C":{"Em":[{"genere":"rock"}]}},"Bm":{"C":{"D":[{"genere":"pop"}],"Em":[{"genere":"pop"}],"G":[{"genere":"soul"}]},"Em":{"G":[{"genere":"soul"}]}},"D":{"Em":{"G":[{"genere":"rock"},{"genere":"pop"}]},"F":{"G":[{"genere":"pop"}]}},"Dm":{"Em":{"F":[{"genere":"pop"}],"G":[{"genere":"soul"}]},"F":{"G":[{"genere":"rock"},{"genere":"pop"}]}},"E":{"F":{"G":[{"genere":"rock"}]}},"Em":{"F":{"G":[{"genere":"rock"},{"genere":"pop"},{"genere":"soul"}]}}},"B":{"C":{"Cm":{"G":[{"genere":"rock"}]}},"E":{"F#":{"F#m":[{"genere":"pop"}]}}},"Bm":{"C":{"Em":{"G":[{"genere":"pop"}]}},"D":{"E":{"G":[{"genere":"rock"}]}}},"C":{"D":{"E":{"G":[{"genere":"rock"},{"genere":"country"}]},"Em":{"G":[{"genere":"rock"},{"genere":"pop"},{"genere":"country"},{"genere":"soul"}]},"F":{"G":[{"genere":"rock"},{"genere":"pop"},{"genere":"soul"}]}},"Dm":{"Em":{"F":[{"genere":"soul"}]},"F":{"G":[{"genere":"pop"}]}}}};

function getTrie(chordList) {
	let output = {};
	for (let i in chordList) {
		let chord = chordList[i];
		if (!output.hasOwnProperty(chord.note1))
			output[chord.note1] = {};
		if (!output[chord.note1].hasOwnProperty(chord.note2))
			output[chord.note1][chord.note2] = {};
		if (!output[chord.note1][chord.note2].hasOwnProperty(chord.note3))
			output[chord.note1][chord.note2][chord.note3] = {};
		if (!output[chord.note1][chord.note2][chord.note3].hasOwnProperty(chord.note4))
			output[chord.note1][chord.note2][chord.note3][chord.note4] = [];
		output[chord.note1][chord.note2][chord.note3][chord.note4].push({genere: chord.genere});
	}
	console.log(JSON.stringify(output));
	return output;
}
